import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./presentation/external/styled/registry/styledRegistry";
import { GlobalStyle } from "./presentation/external/styled/global";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StyledComponentsRegistry>
        {children}
      </StyledComponentsRegistry>
      <GlobalStyle />
      </body>
    </html>
  );
}
